### ISSUE TITLE
Load custom dict with locale set on non supported one

### ISSUE THREAD

**Issue by aletundo** [arandilopez/laravel-profane#2]
Hi @arandilopez ! First of all I really appreciated your package.

I'm trying to use a custom dictionary file loading it as following:
`'name' => 'required|string|max:100|profane:en,' . resource_path('lang/it/profane.php')`

My locale is set on `it` language which is not supported out of the box. I'm stuck on this exception:

`ErrorException(code: 0): include(it): failed to open stream: No such file or directory at /var/www/myproject/vendor/arandilopez/laravel-profane/src/ProfaneValidator.php:85`

I debugged your code a little bit. I noticed that the variable `$dictionary` used in line `ProfaneValidator.php:85` contains the locale value. So it expects a path but it is the locale string.

As ultimate test I tried to change `$dict = include($dictionary);` on line 85 with `$dict = include(resource_path('path/to/my/dict.php');` at it worked.

Thank you!

**Comment by arandilopez** [comment]
Hi @aletundo. Thanks for this issue.. I will try replicate it. Would you lend me your `it` dictionary to test it? You can also help me to include that dict to the base, like `en` and `es` as well

Regards!

**Comment by aletundo** [comment]
> Would you lend me your `it` dictionary to test it?

Yes, for sure!
[it_dict.txt](https://github.com/arandilopez/laravel-profane/files/1034195/it_dict.txt)

It was a merge of the dictionaries from [banbuilder](https://github.com/snipe/banbuilder) and [Laravel5-Profanity-Filter](https://github.com/Askedio/Laravel5-Profanity-Filter).

> You can also help me to include that dict to the base, like en and es as well.

Okay! I may make a pull a request.. I have just to give look at your unit tests.

**Comment by arandilopez** [comment]
@aletundo Well, the error is because I don't have a `it.php` in the dicts directory... Just a validation more to wont try to load a locale missing file when you do `'locale' => 'it'`. But the file path you passed will be loaded like here:

```php
<?php
// ....

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|profane:en,es,'.resource_path('lang/it/dict.php')
        ]);

        // In case it passes
        return response()->json(['name' => $request->input('name')]);
    }

```

You can send a pull request to add that `it.php` dictionary you have.. I don't know Italian but I trust in you 😄 

Regards!

**Comment by aletundo** [comment]
@arandilopez I got the point! It works now! 

I'm going to make a pull request asap.
