### ISSUE TITLE
Doesn't seem to work in Laravel 5.5

### ISSUE THREAD

**Issue by sciku1** [arandilopez/laravel-profane#34]
Ran the composer require, added it to the service providers in config/app.php. Pretty sure it's because Laravel changed the way to add validation rules.

**Comment by sciku1** [comment]
It was my mistake! Spoke too soon!

**Comment by johannesschobel** [comment]
is this open or closed? haha

**Comment by arandilopez** [comment]
Should work with Laravel 6
