### ISSUE TITLE
Hell(o)

### ISSUE THREAD

**Issue by benrolfe** [arandilopez/laravel-profane#40]
I see in the commit log that "hell" has been removed.

However this hasn't been reflected in v0.3.5. Can this be published for us to use?

Thanks!

**Comment by arandilopez** [comment]
Hi @benrolfe, thanks for your comment. Let me take some time to check this. I have to review PRs and check for Laravel 6 compatibility too. Hope to get this done soon.

**Comment by benrolfe** [comment]
@arandilopez Thanks. Could you update this issue when those changes have been released? Thanks for your hard work. 👍

**Comment by arandilopez** [comment]
@benrolfe I released a new tag v0.4.0, hope it will help you
