### ISSUE TITLE
Should match exact word, but not always

### ISSUE THREAD

**Issue by arandilopez** [arandilopez/laravel-profane#9]
## The case:

Supose user enter in a bio or something like that the word **class**, if we validate it against the validator, it will say that contains vulgar content. `class ~= ass`

So, Validator should only match `ass`. The solution may will be in `Str#containsCaseless` with a regex like: `/\b$needle\b/iu`.

### Ok... now the other part...

Supose someone enter as username **sucker96** (i donno why, but let's supose it). If we validate that with the change above, validator will not argue anything... without the change above, it will say that the username contains vulgar content.

Should it need be fixed that way?

**Comment by LucasLeandro1204** [comment]
Just use a second bool parameter, if set to true, it will verify if the string contains instead equal.

**Comment by rachids** [comment]
As you said in #36, it could be nice to have an option to activate it or not depending on the field under validation.

In your exemple, I would deactivate it for `username` but not for `bio`.

**Comment by arandilopez** [comment]
Thanks for your comment @rachids. I found the time and inspiriation to fix this.
